"""Local search heuristic: improve a seed assignment via affinity-guided swaps.

Candidate swaps are generated by proximity to affinity neighbors: for each SKU i
and each affinity neighbor k of i, propose swapping i with the SKU currently
occupying k's location. This captures moves where a_ij = 0 but swapping i and j
brings i closer to its true affinity targets.
"""

from __future__ import annotations

import numpy as np

from ..slotting import Assignment, SlottingInstance, swap_cost_delta
from .base import method_registry
from .demand_greedy import DemandGreedySlotting


def _affinity_neighbors(affinity_csr, sku_idx: int) -> np.ndarray:
    """Return indices of SKUs with nonzero affinity to sku_idx."""
    start, end = affinity_csr.indptr[sku_idx], affinity_csr.indptr[sku_idx + 1]
    return affinity_csr.indices[start:end]


@method_registry.register("swap_search")
class SwapSearchSlotting:
    """Affinity-guided local search via iterative swaps.

    Generates swap candidates dynamically: for each SKU i and each affinity
    neighbor k of i, proposes swapping i with the SKU currently at k's location.

    Rationale: the goal is to bring SKUs with high affinity close together.
    Swapping i with whoever is at k's location is the direct move that achieves
    this. The pair (i, j) may have a_ij = 0, but the swap is still beneficial
    because it brings i near k (where a_ik > 0).

    Algorithm:
    1. Seed: DemandGreedy (or any SlottingMethod).
    2. Per pass: for each SKU i, for each affinity neighbor k of i,
       propose swap(i, sku_at(location_of(k))). Accept if delta < 0.
    3. Stop when no improving swap is found in a full pass.

    Complexity per pass: O(n · deg_avg · swap_cost_delta_cost)
    where swap_cost_delta_cost = O(deg_avg). Total per pass: O(n · deg²).

    Parameters
    ----------
    seed_method :
        Initial assignment generator. Defaults to DemandGreedySlotting.
    lam : float
        Weight λ ∈ [0, 1] for C = λ·L + (1-λ)·Q.
    max_passes : int
        Maximum passes over all SKUs.
    """

    name = "swap_search"

    def __init__(self, seed_method=None, *, lam: float = 0.5, max_passes: int = 50):
        self.seed_method = seed_method or DemandGreedySlotting()
        self.lam = float(lam)
        self.max_passes = int(max_passes)
        if not 0.0 <= self.lam <= 1.0:
            raise ValueError(f"lam must be in [0, 1], got {self.lam}.")

    def solve(self, instance: SlottingInstance) -> Assignment:
        """Find improved assignment via proximity-guided local search.

        Returns
        -------
        Assignment
            Locally optimal assignment: no improving swap exists among
            the dynamically generated candidates.
        """
        assignment = self.seed_method.solve(instance)
        affinity = instance.affinity.tocsr()

        for _ in range(self.max_passes):
            improved = False

            for sku_i_idx in range(instance.n_skus):
                sku_i = instance.sku_id(sku_i_idx)
                neighbors = _affinity_neighbors(affinity, sku_i_idx)

                if len(neighbors) == 0:
                    continue

                # For each affinity neighbor k, propose swapping i with whoever
                # is currently at k's location. This moves i near k directly.
                for sku_k_idx in neighbors:
                    sku_k = instance.sku_id(sku_k_idx)
                    loc_k = assignment.location_of(sku_k)
                    sku_j = assignment.sku_at(loc_k)  # occupant of k's location = k itself

                    # swap(i, k) — move i to k's location, k to i's location.
                    if sku_i == sku_j:
                        continue

                    delta = swap_cost_delta(assignment, instance, sku_i, sku_j, lam=self.lam)

                    if delta < 0.0:
                        assignment.swap(sku_i, sku_j)
                        improved = True

            if not improved:
                break

        return assignment
